### ISSUE TITLE
Can't get attribute 'Vocabulary'

### ISSUE THREAD

**Issue by L0ittle** [parksunwoo/show_attend_and_tell_pytorch#4]
when I train this like 'python main.py'
it will return with the error as the following:

> _Traceback (most recent call last):
>   File "main.py", line 298, in <module>
>     main(args)
>   File "main.py", line 57, in main
>     vocab = pickle.load(f)
> AttributeError: Can't get attribute 'Vocabulary' on <module '__main__' from 'main.py'>_

I have found nothing to resolve it

**Comment by ghrua** [comment]
To quickly fix this bug, you could add this line at  the top of `main.py`

```
from prepro import *
```
Or you could reformat the code, such as putting the code related to the `vocab` to a new file `vocab.py`.

**Comment by L0ittle** [comment]
Thanks a lot for your reply, it have got resolved.

**Comment by y78h11b09** [comment]
@L0ittle, hello, how did you solved it? can you tell me  what do you do? thanks !
